# -*- coding: utf-8 -*-
"""
Created on Mon Feb  6 19:16:00 2023

@author: user
"""

class all1():
    
    def ANT():
        kor1 = """
     	select A.TRD_DT,A.ETF_CD,ETF_NM,SUM,INVEST_GB  from (SELECT CONVERT(VARCHAR(20),CONVERT(datetime,TR_YMD,1),120) TRD_DT,ETF_CD,SUM(NET_AMT) OVER (PARTITION BY ETF_CD ORDER BY TR_YMD ASC) SUM,INVEST_GB FROM FN_ETFINV 
    WHERE INVEST_GB=8 ) A, FN_ETFINFO B WHERE A.ETF_CD=B.ETF_CD  AND B.TR_YMD=(SELECT MAX(TR_YMD) FROM FN_ETFINFO WHERE TR_YMD<=GETDATE()) ORDER BY A.ETF_CD ASC,A.TRD_DT ASC
         """
        return kor1


    def FINV():
        kor1 = """
select A.TRD_DT,A.ETF_CD,ETF_NM,SUM,INVEST_GB  from (SELECT CONVERT(VARCHAR(20),CONVERT(datetime,TR_YMD,1),120) TRD_DT,ETF_CD,SUM(NET_AMT) OVER (PARTITION BY ETF_CD ORDER BY TR_YMD ASC) SUM,INVEST_GB FROM FN_ETFINV 
WHERE INVEST_GB=1 ) A, FN_ETFINFO B WHERE A.ETF_CD=B.ETF_CD  AND B.TR_YMD=(SELECT MAX(TR_YMD) FROM FN_ETFINFO WHERE TR_YMD<=GETDATE()) ORDER BY A.ETF_CD ASC,A.TRD_DT ASC
         """
        return kor1

    def BK():
        kor1 = """
    	select A.TRD_DT,A.ETF_CD,ETF_NM,SUM,INVEST_GB  from (SELECT CONVERT(VARCHAR(20),CONVERT(datetime,TR_YMD,1),120) TRD_DT,ETF_CD,SUM(NET_AMT) OVER (PARTITION BY ETF_CD ORDER BY TR_YMD ASC) SUM,INVEST_GB FROM FN_ETFINV 
   WHERE INVEST_GB=4 ) A, FN_ETFINFO B WHERE A.ETF_CD=B.ETF_CD  AND B.TR_YMD=(SELECT MAX(TR_YMD) FROM FN_ETFINFO WHERE TR_YMD<=GETDATE()) ORDER BY A.ETF_CD ASC,A.TRD_DT ASC
         """
        return kor1

    def INS():
        kor1 = """
    	select A.TRD_DT,A.ETF_CD,ETF_NM,SUM,INVEST_GB  from (SELECT CONVERT(VARCHAR(20),CONVERT(datetime,TR_YMD,1),120) TRD_DT,ETF_CD,SUM(NET_AMT) OVER (PARTITION BY ETF_CD ORDER BY TR_YMD ASC) SUM,INVEST_GB FROM FN_ETFINV 
   WHERE INVEST_GB=2 ) A, FN_ETFINFO B WHERE A.ETF_CD=B.ETF_CD  AND B.TR_YMD=(SELECT MAX(TR_YMD) FROM FN_ETFINFO WHERE TR_YMD<=GETDATE()) ORDER BY A.ETF_CD ASC,A.TRD_DT ASC
         """
        return kor1

    def ALIEN():
        kor1 = """
     	select A.TRD_DT,A.ETF_CD,ETF_NM,SUM,INVEST_GB  from (SELECT CONVERT(VARCHAR(20),CONVERT(datetime,TR_YMD,1),120) TRD_DT,ETF_CD,SUM(NET_AMT) OVER (PARTITION BY ETF_CD ORDER BY TR_YMD ASC) SUM,INVEST_GB FROM FN_ETFINV 
    WHERE INVEST_GB=9 ) A, FN_ETFINFO B WHERE A.ETF_CD=B.ETF_CD  AND B.TR_YMD=(SELECT MAX(TR_YMD) FROM FN_ETFINFO WHERE TR_YMD<=GETDATE()) ORDER BY A.ETF_CD ASC,A.TRD_DT ASC
         """
        return kor1    
    
    def TRUST():
        kor1 = """
     	select A.TRD_DT,A.ETF_CD,ETF_NM,SUM,INVEST_GB  from (SELECT CONVERT(VARCHAR(20),CONVERT(datetime,TR_YMD,1),120) TRD_DT,ETF_CD,SUM(NET_AMT) OVER (PARTITION BY ETF_CD ORDER BY TR_YMD ASC) SUM,INVEST_GB FROM FN_ETFINV 
    WHERE INVEST_GB=3 ) A, FN_ETFINFO B WHERE A.ETF_CD=B.ETF_CD  AND B.TR_YMD=(SELECT MAX(TR_YMD) FROM FN_ETFINFO WHERE TR_YMD<=GETDATE()) ORDER BY A.ETF_CD ASC,A.TRD_DT ASC
         """
        return kor1    

    def PENS():
        kor1 = """
     	select A.TRD_DT,A.ETF_CD,ETF_NM,SUM,INVEST_GB  from (SELECT CONVERT(VARCHAR(20),CONVERT(datetime,TR_YMD,1),120) TRD_DT,ETF_CD,SUM(NET_AMT) OVER (PARTITION BY ETF_CD ORDER BY TR_YMD ASC) SUM,INVEST_GB FROM FN_ETFINV 
    WHERE INVEST_GB=6 ) A, FN_ETFINFO B WHERE A.ETF_CD=B.ETF_CD  AND B.TR_YMD=(SELECT MAX(TR_YMD) FROM FN_ETFINFO WHERE TR_YMD<=GETDATE()) ORDER BY A.ETF_CD ASC,A.TRD_DT ASC
         """
        return kor1     
    
    def PEF():
        kor1 = """
     	select A.TRD_DT,A.ETF_CD,ETF_NM,SUM,INVEST_GB  from (SELECT CONVERT(VARCHAR(20),CONVERT(datetime,TR_YMD,1),120) TRD_DT,ETF_CD,SUM(NET_AMT) OVER (PARTITION BY ETF_CD ORDER BY TR_YMD ASC) SUM,INVEST_GB FROM FN_ETFINV 
    WHERE INVEST_GB=31 ) A, FN_ETFINFO B WHERE A.ETF_CD=B.ETF_CD  AND B.TR_YMD=(SELECT MAX(TR_YMD) FROM FN_ETFINFO WHERE TR_YMD<=GETDATE()) ORDER BY A.ETF_CD ASC,A.TRD_DT ASC
         """
        return kor1    
    
    def CORP():
        kor1 = """
     	select A.TRD_DT,A.ETF_CD,ETF_NM,SUM,INVEST_GB  from (SELECT CONVERT(VARCHAR(20),CONVERT(datetime,TR_YMD,1),120) TRD_DT,ETF_CD,SUM(NET_AMT) OVER (PARTITION BY ETF_CD ORDER BY TR_YMD ASC) SUM,INVEST_GB FROM FN_ETFINV 
    WHERE INVEST_GB=0 ) A, FN_ETFINFO B WHERE A.ETF_CD=B.ETF_CD  AND B.TR_YMD=(SELECT MAX(TR_YMD) FROM FN_ETFINFO WHERE TR_YMD<=GETDATE()) ORDER BY A.ETF_CD ASC,A.TRD_DT ASC
         """
        return kor1 